package com.huaixuan.network.biz.domain.supplier;

import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Date;

public class Supplier implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = -1152835333617647974L;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.id
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private Long              id;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.name
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private String            name;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.short_name
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private String            shortName;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.linkman
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private String            linkman;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.tel
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private String            tel;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.payment
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private String            payment;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.mobile
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private String            mobile;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.email
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private String            email;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.address
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private String            address;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.grade
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private String            grade;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.marketing
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private String            marketing;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.bank
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private String            bank;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.bank_num
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private String            bankNum;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.payee
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private String            payee;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.remark
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private String            remark;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.brand
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private String            brand;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.status
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private String            status;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.gmt_create
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private Date              gmtCreate;

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to
     * the database column ioss_supplier.gmt_modify
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    private Date              gmtModify;

    private String            chargeMan;

    private String            fax;

    private String            im;

    // 及时到货�
    private double            arrivePer;

    // �货率
    private double            returnPer;

    public String getChargeMan() {
        return chargeMan;
    }

    public void setChargeMan(String chargeMan) {
        this.chargeMan = chargeMan;
    }

    public String getFax() {
        return fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getIm() {
        return im;
    }

    public void setIm(String im) {
        this.im = im;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.id
     * 
     * @return the value of ioss_supplier.id
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.id
     * 
     * @param id
     *            the value for ioss_supplier.id
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.name
     * 
     * @return the value of ioss_supplier.name
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public String getName() {
        return name;
    }

    /**
     * 用于在URL中传�
     * @return String
     * @author chenyan 2010/03/24
     */
    public String getNameUrl() {
        try {
            return URLEncoder.encode(name, "utf8");
        } catch (UnsupportedEncodingException e) {
            return null;
        }
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.name
     * 
     * @param name
     *            the value for ioss_supplier.name
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.short_name
     * 
     * @return the value of ioss_supplier.short_name
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.short_name
     * 
     * @param shortName
     *            the value for ioss_supplier.short_name
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.linkman
     * 
     * @return the value of ioss_supplier.linkman
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.linkman
     * 
     * @param linkman
     *            the value for ioss_supplier.linkman
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.tel
     * 
     * @return the value of ioss_supplier.tel
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.tel
     * 
     * @param tel
     *            the value for ioss_supplier.tel
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.payment
     * 
     * @return the value of ioss_supplier.payment
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public String getPayment() {
        return payment;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.payment
     * 
     * @param payment
     *            the value for ioss_supplier.payment
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setPayment(String payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.mobile
     * 
     * @return the value of ioss_supplier.mobile
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.mobile
     * 
     * @param mobile
     *            the value for ioss_supplier.mobile
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.email
     * 
     * @return the value of ioss_supplier.email
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.email
     * 
     * @param email
     *            the value for ioss_supplier.email
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.address
     * 
     * @return the value of ioss_supplier.address
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.address
     * 
     * @param address
     *            the value for ioss_supplier.address
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.grade
     * 
     * @return the value of ioss_supplier.grade
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.grade
     * 
     * @param grade
     *            the value for ioss_supplier.grade
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.marketing
     * 
     * @return the value of ioss_supplier.marketing
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public String getMarketing() {
        return marketing;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.marketing
     * 
     * @param marketing
     *            the value for ioss_supplier.marketing
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setMarketing(String marketing) {
        this.marketing = marketing;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.bank
     * 
     * @return the value of ioss_supplier.bank
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.bank
     * 
     * @param bank
     *            the value for ioss_supplier.bank
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setBank(String bank) {
        this.bank = bank;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.bank_num
     * 
     * @return the value of ioss_supplier.bank_num
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public String getBankNum() {
        return bankNum;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.bank_num
     * 
     * @param bankNum
     *            the value for ioss_supplier.bank_num
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setBankNum(String bankNum) {
        this.bankNum = bankNum;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.payee
     * 
     * @return the value of ioss_supplier.payee
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public String getPayee() {
        return payee;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.payee
     * 
     * @param payee
     *            the value for ioss_supplier.payee
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setPayee(String payee) {
        this.payee = payee;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.remark
     * 
     * @return the value of ioss_supplier.remark
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.remark
     * 
     * @param remark
     *            the value for ioss_supplier.remark
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.brand
     * 
     * @return the value of ioss_supplier.brand
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.brand
     * 
     * @param brand
     *            the value for ioss_supplier.brand
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.status
     * 
     * @return the value of ioss_supplier.status
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.status
     * 
     * @param status
     *            the value for ioss_supplier.status
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.gmt_create
     * 
     * @return the value of ioss_supplier.gmt_create
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.gmt_create
     * 
     * @param gmtCreate
     *            the value for ioss_supplier.gmt_create
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the
     * value of the database column ioss_supplier.gmt_modify
     * 
     * @return the value of ioss_supplier.gmt_modify
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the
     * value of the database column ioss_supplier.gmt_modify
     * 
     * @param gmtModify
     *            the value for ioss_supplier.gmt_modify
     * 
     * @abatorgenerated Tue Jul 14 10:59:01 CST 2009
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    public double getArrivePer() {
        return arrivePer;
    }

    public void setArrivePer(double arrivePer) {
        this.arrivePer = arrivePer;
    }

    public double getReturnPer() {
        return returnPer;
    }

    public void setReturnPer(double returnPer) {
        this.returnPer = returnPer;
    }

    // public String getFormatSupplierId() {
    // String formatSupplierId = "";
    // if (this.id != null) {
    // String supplierId = (this.id).toString();
    // if (supplierId.length() >= 4) {
    // return supplierId;
    // }
    // for (int i = 0; i < 4 - supplierId.length(); i++) {
    // formatSupplierId = "0" + supplierId;
    // }
    // }
    // return formatSupplierId;
    // }
}